// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Album         string
	Artist        string
	Customer      string
	Employee      string
	Genre         string
	Invoice       string
	InvoiceLine   string
	MediaType     string
	Playlist      string
	PlaylistTrack string
	Track         string
}{
	Album:         "Album",
	Artist:        "Artist",
	Customer:      "Customer",
	Employee:      "Employee",
	Genre:         "Genre",
	Invoice:       "Invoice",
	InvoiceLine:   "InvoiceLine",
	MediaType:     "MediaType",
	Playlist:      "Playlist",
	PlaylistTrack: "PlaylistTrack",
	Track:         "Track",
}
