// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Genre is an object representing the database table.
type Genre struct {
	GenreId int64       `boil:"GenreId" json:"GenreId" toml:"GenreId" yaml:"GenreId"`
	Name    null.String `boil:"Name" json:"Name,omitempty" toml:"Name" yaml:"Name,omitempty"`

	R *genreR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L genreL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GenreColumns = struct {
	GenreId string
	Name    string
}{
	GenreId: "GenreId",
	Name:    "Name",
}

var GenreTableColumns = struct {
	GenreId string
	Name    string
}{
	GenreId: "Genre.GenreId",
	Name:    "Genre.Name",
}

// Generated where

var GenreWhere = struct {
	GenreId whereHelperint64
	Name    whereHelpernull_String
}{
	GenreId: whereHelperint64{field: "\"Genre\".\"GenreId\""},
	Name:    whereHelpernull_String{field: "\"Genre\".\"Name\""},
}

// GenreRels is where relationship names are stored.
var GenreRels = struct {
	GenreIdTracks string
}{
	GenreIdTracks: "GenreIdTracks",
}

// genreR is where relationships are stored.
type genreR struct {
	GenreIdTracks TrackSlice `boil:"GenreIdTracks" json:"GenreIdTracks" toml:"GenreIdTracks" yaml:"GenreIdTracks"`
}

// NewStruct creates a new relationship struct
func (*genreR) NewStruct() *genreR {
	return &genreR{}
}

// genreL is where Load methods for each relationship are stored.
type genreL struct{}

var (
	genreAllColumns            = []string{"GenreId", "Name"}
	genreColumnsWithoutDefault = []string{"Name"}
	genreColumnsWithDefault    = []string{"GenreId"}
	genrePrimaryKeyColumns     = []string{"GenreId"}
)

type (
	// GenreSlice is an alias for a slice of pointers to Genre.
	// This should almost always be used instead of []Genre.
	GenreSlice []*Genre
	// GenreHook is the signature for custom Genre hook methods
	GenreHook func(context.Context, boil.ContextExecutor, *Genre) error

	genreQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	genreType                 = reflect.TypeOf(&Genre{})
	genreMapping              = queries.MakeStructMapping(genreType)
	genrePrimaryKeyMapping, _ = queries.BindMapping(genreType, genreMapping, genrePrimaryKeyColumns)
	genreInsertCacheMut       sync.RWMutex
	genreInsertCache          = make(map[string]insertCache)
	genreUpdateCacheMut       sync.RWMutex
	genreUpdateCache          = make(map[string]updateCache)
	genreUpsertCacheMut       sync.RWMutex
	genreUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var genreBeforeInsertHooks []GenreHook
var genreBeforeUpdateHooks []GenreHook
var genreBeforeDeleteHooks []GenreHook
var genreBeforeUpsertHooks []GenreHook

var genreAfterInsertHooks []GenreHook
var genreAfterSelectHooks []GenreHook
var genreAfterUpdateHooks []GenreHook
var genreAfterDeleteHooks []GenreHook
var genreAfterUpsertHooks []GenreHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Genre) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Genre) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Genre) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Genre) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Genre) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Genre) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Genre) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Genre) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Genre) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range genreAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddGenreHook registers your hook function for all future operations.
func AddGenreHook(hookPoint boil.HookPoint, genreHook GenreHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		genreBeforeInsertHooks = append(genreBeforeInsertHooks, genreHook)
	case boil.BeforeUpdateHook:
		genreBeforeUpdateHooks = append(genreBeforeUpdateHooks, genreHook)
	case boil.BeforeDeleteHook:
		genreBeforeDeleteHooks = append(genreBeforeDeleteHooks, genreHook)
	case boil.BeforeUpsertHook:
		genreBeforeUpsertHooks = append(genreBeforeUpsertHooks, genreHook)
	case boil.AfterInsertHook:
		genreAfterInsertHooks = append(genreAfterInsertHooks, genreHook)
	case boil.AfterSelectHook:
		genreAfterSelectHooks = append(genreAfterSelectHooks, genreHook)
	case boil.AfterUpdateHook:
		genreAfterUpdateHooks = append(genreAfterUpdateHooks, genreHook)
	case boil.AfterDeleteHook:
		genreAfterDeleteHooks = append(genreAfterDeleteHooks, genreHook)
	case boil.AfterUpsertHook:
		genreAfterUpsertHooks = append(genreAfterUpsertHooks, genreHook)
	}
}

// One returns a single genre record from the query.
func (q genreQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Genre, error) {
	o := &Genre{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for Genre")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Genre records from the query.
func (q genreQuery) All(ctx context.Context, exec boil.ContextExecutor) (GenreSlice, error) {
	var o []*Genre

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Genre slice")
	}

	if len(genreAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Genre records in the query.
func (q genreQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count Genre rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q genreQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if Genre exists")
	}

	return count > 0, nil
}

// GenreIdTracks retrieves all the Track's Tracks with an executor via GenreId column.
func (o *Genre) GenreIdTracks(mods ...qm.QueryMod) trackQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"Track\".\"GenreId\"=?", o.GenreId),
	)

	query := Tracks(queryMods...)
	queries.SetFrom(query.Query, "\"Track\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"Track\".*"})
	}

	return query
}

// LoadGenreIdTracks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (genreL) LoadGenreIdTracks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGenre interface{}, mods queries.Applicator) error {
	var slice []*Genre
	var object *Genre

	if singular {
		object = maybeGenre.(*Genre)
	} else {
		slice = *maybeGenre.(*[]*Genre)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &genreR{}
		}
		args = append(args, object.GenreId)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &genreR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.GenreId) {
					continue Outer
				}
			}

			args = append(args, obj.GenreId)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`Track`),
		qm.WhereIn(`Track.GenreId in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Track")
	}

	var resultSlice []*Track
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Track")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on Track")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for Track")
	}

	if len(trackAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.GenreIdTracks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &trackR{}
			}
			foreign.R.GenreIdGenre = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.GenreId, foreign.GenreId) {
				local.R.GenreIdTracks = append(local.R.GenreIdTracks, foreign)
				if foreign.R == nil {
					foreign.R = &trackR{}
				}
				foreign.R.GenreIdGenre = local
				break
			}
		}
	}

	return nil
}

// AddGenreIdTracks adds the given related objects to the existing relationships
// of the Genre, optionally inserting them as new records.
// Appends related to o.R.GenreIdTracks.
// Sets related.R.GenreIdGenre appropriately.
func (o *Genre) AddGenreIdTracks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Track) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.GenreId, o.GenreId)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"Track\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 0, []string{"GenreId"}),
				strmangle.WhereClause("\"", "\"", 0, trackPrimaryKeyColumns),
			)
			values := []interface{}{o.GenreId, rel.TrackId}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.GenreId, o.GenreId)
		}
	}

	if o.R == nil {
		o.R = &genreR{
			GenreIdTracks: related,
		}
	} else {
		o.R.GenreIdTracks = append(o.R.GenreIdTracks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &trackR{
				GenreIdGenre: o,
			}
		} else {
			rel.R.GenreIdGenre = o
		}
	}
	return nil
}

// SetGenreIdTracks removes all previously related items of the
// Genre replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.GenreIdGenre's GenreIdTracks accordingly.
// Replaces o.R.GenreIdTracks with related.
// Sets related.R.GenreIdGenre's GenreIdTracks accordingly.
func (o *Genre) SetGenreIdTracks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Track) error {
	query := "update \"Track\" set \"GenreId\" = null where \"GenreId\" = ?"
	values := []interface{}{o.GenreId}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.GenreIdTracks {
			queries.SetScanner(&rel.GenreId, nil)
			if rel.R == nil {
				continue
			}

			rel.R.GenreIdGenre = nil
		}

		o.R.GenreIdTracks = nil
	}
	return o.AddGenreIdTracks(ctx, exec, insert, related...)
}

// RemoveGenreIdTracks relationships from objects passed in.
// Removes related items from R.GenreIdTracks (uses pointer comparison, removal does not keep order)
// Sets related.R.GenreIdGenre.
func (o *Genre) RemoveGenreIdTracks(ctx context.Context, exec boil.ContextExecutor, related ...*Track) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.GenreId, nil)
		if rel.R != nil {
			rel.R.GenreIdGenre = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("GenreId")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.GenreIdTracks {
			if rel != ri {
				continue
			}

			ln := len(o.R.GenreIdTracks)
			if ln > 1 && i < ln-1 {
				o.R.GenreIdTracks[i] = o.R.GenreIdTracks[ln-1]
			}
			o.R.GenreIdTracks = o.R.GenreIdTracks[:ln-1]
			break
		}
	}

	return nil
}

// Genres retrieves all the records using an executor.
func Genres(mods ...qm.QueryMod) genreQuery {
	mods = append(mods, qm.From("\"Genre\""))
	return genreQuery{NewQuery(mods...)}
}

// FindGenre retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGenre(ctx context.Context, exec boil.ContextExecutor, genreId int64, selectCols ...string) (*Genre, error) {
	genreObj := &Genre{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"Genre\" where \"GenreId\"=?", sel,
	)

	q := queries.Raw(query, genreId)

	err := q.Bind(ctx, exec, genreObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from Genre")
	}

	if err = genreObj.doAfterSelectHooks(ctx, exec); err != nil {
		return genreObj, err
	}

	return genreObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Genre) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Genre provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(genreColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	genreInsertCacheMut.RLock()
	cache, cached := genreInsertCache[key]
	genreInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			genreAllColumns,
			genreColumnsWithDefault,
			genreColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(genreType, genreMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(genreType, genreMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"Genre\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"Genre\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into Genre")
	}

	if !cached {
		genreInsertCacheMut.Lock()
		genreInsertCache[key] = cache
		genreInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Genre.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Genre) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	genreUpdateCacheMut.RLock()
	cache, cached := genreUpdateCache[key]
	genreUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			genreAllColumns,
			genrePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update Genre, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"Genre\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, genrePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(genreType, genreMapping, append(wl, genrePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update Genre row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for Genre")
	}

	if !cached {
		genreUpdateCacheMut.Lock()
		genreUpdateCache[key] = cache
		genreUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q genreQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for Genre")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for Genre")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GenreSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), genrePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"Genre\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, genrePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in genre slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all genre")
	}
	return rowsAff, nil
}

// Delete deletes a single Genre record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Genre) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Genre provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), genrePrimaryKeyMapping)
	sql := "DELETE FROM \"Genre\" WHERE \"GenreId\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from Genre")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for Genre")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q genreQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no genreQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from Genre")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Genre")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GenreSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(genreBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), genrePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"Genre\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, genrePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from genre slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for Genre")
	}

	if len(genreAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Genre) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGenre(ctx, exec, o.GenreId)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GenreSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GenreSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), genrePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"Genre\".* FROM \"Genre\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, genrePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GenreSlice")
	}

	*o = slice

	return nil
}

// GenreExists checks if the Genre row exists.
func GenreExists(ctx context.Context, exec boil.ContextExecutor, genreId int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"Genre\" where \"GenreId\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, genreId)
	}
	row := exec.QueryRowContext(ctx, sql, genreId)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if Genre exists")
	}

	return exists, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Genre) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no Genre provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(genreColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	genreUpsertCacheMut.RLock()
	cache, cached := genreUpsertCache[key]
	genreUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			genreAllColumns,
			genreColumnsWithDefault,
			genreColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			genreAllColumns,
			genrePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert Genre, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(genrePrimaryKeyColumns))
			copy(conflict, genrePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"Genre\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(genreType, genreMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(genreType, genreMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert Genre")
	}

	if !cached {
		genreUpsertCacheMut.Lock()
		genreUpsertCache[key] = cache
		genreUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
